### PR TITLE
Support custom config values

### PR DESCRIPTION
**Pull request by NoelDeMartin**
I'm trying to use my [local_behatsnapshots](https://github.com/NoelDeMartin/moodle-local_behatsnapshots/) plugin with the runner, and one of the issues I am facing is that I need to set some custom config values.

I could have solved this by adding a new variable and setting it manually like we're already doing with others (like `DBTYPE`, `BEHAT_INCREASE_TIMEOUT`, etc.). But I think that's not the best approach for a couple of reasons.

First, I'm not sure if I want to hard-code my plugin's config names. I'm still working on it and I may want to change the naming. I also don't like the idea of coupling this repository to my plugin which is a bit experimental.

And second, I've faced similar problems in the past that I think could be solved using this. For example, [MDL-74293](https://tracker.moodle.org/browse/MDL-74293).

In any case, if you don't like the idea I can open a new PR just adding a new env variable to set the config for my plugin.

### CODE REVIEW

**Comment by stronk7** [comment]
I'm also pinging to @andrewnicols for his opinion here...

Personally it's ok for me to allow that "hodgepodge" via to add CFG settings.

I just have 2 observations about that:
1. Maybe we should find a way to also support `CFG->forced_plugin_settings` so any plugin config can be also specified? Note that is requires this to be set in order to get them configured within Behat: `$CFG->behat_extraallowedsettings = array('forced_plugin_settings');` . Or maybe we don't need anything because both are, indeed, CFG settings and can be configured using the "hodgepodge" added here? Real example, to see if it's doable with current implementation or no: I've this in my dev `config.php` file:
```
// To allow pdf tests, clamav...
$CFG->behat_extraallowedsettings = array('forced_plugin_settings');
...
$CFG->forced_plugin_settings['analytics']['predictionsprocessor'] = '\mlbackend_python\processor'; // Comment to use PHP backend.
...
$CFG->forced_plugin_settings['assignfeedback_editpdf']['gspath'] = '/opt/local/bin/gs';
$CFG->forced_plugin_settings['backup']['backup_encryptkey'] = 'xxxxxxxx/xxxxxxxxxx=';
...
```
2. I'm not 100% sure about having the new feature called from within the `set_behat_configuration()`, IMO it deserves to be standalone stuff (class, just function, ...?) It can be also interesting for PHPUnit or other, future, type of jobs.

In any case, as said, about the overall idea of having a method to inject CFG settings in general, it's ok for me (and only the really critical/job related ones will need proper variables.

Ciao :-)

**Comment by stronk7** [comment]
Friendly ping to the daddy of the runner, to see if we can consider the injection of CFGs via JSON acceptable enough (apart from the 2 points commented above). @andrewnicols

**Comment by stronk7** [comment]
Hi,

while putting under testing the new runner architecture that we are starting to use, I've used this to see how hard would be to add a new feature to it. And I'm really happy about how easy it was!

I've ended with this commit, that adds a new module (moodle-config) to the runner, and applies it to both phpunit and behat. And, it supports both global and component configuration settings.

https://github.com/stronk7/moodle-ci-runner/commit/6c5858647c72ca2b3442b1e2c5866ef07b97bcd2

The commit above will be soon available in the ["split" branch of moodle-ci-runner.](https://github.com/moodlehq/moodle-ci-runner/tree/split) You can switch to it for local tests or, also, use the SPLIT runner @ CIs (instead of the STABLE one that is the current one).

Surely once it's checked that it's working as expected (i've tried here modifying a few global and plugin settings) in the new runner, we can close this and done.

Ciao :-)

**Comment by stronk7** [comment]
I've testing the new `MOODLE_CONFIG` locally, to try to get those behat snapshots scenarios running and this is what I'm getting (summary of output):

```
============================================================================
= Job summary <<<
============================================================================
== JOBTYPE: behat
== Build Id: 92448
== Workspace: /var/folders/3b/4q5trjyj3h99k0wdts3fm8tc0000gn/T/tmp.VazDr8PxgL/workspace
== Code directory: /Users/stronk7/git_moodle/ci-tests
== Shared directory: /var/folders/3b/4q5trjyj3h99k0wdts3fm8tc0000gn/T/tmp.VazDr8PxgL/workspace/92448
== UUID / Container suffix: b1741e38b2e2034e
== Environment: /var/folders/3b/4q5trjyj3h99k0wdts3fm8tc0000gn/T/tmp.VazDr8PxgL/workspace/92448/moodle-ci-runner.env
== GIT commit: 859df15e73a331198adc43f957ab5e033b3c26ca
== Moodle branch (version.php): 404
== PHP version: 8.1
== DBTYPE: pgsql
== DBTAG: 13
== DBREPLICAS: 0
== RUNCOUNT: 1
== BROWSER: chrome
== BROWSER_DEBUG: 
== BROWSER_HEADLESS: 
== BEHAT_SUITE: 
== BEHAT_TAGS: @app&&@local_behatsnapshots
== BEHAT_NAME: 
== BEHAT_PARALLEL: 1
== BEHAT_RERUNS: 1
== BEHAT_TIMING_FILENAME: timing_test.json
== BEHAT_INCREASE_TIMEOUT: 2
== MOODLE_CONFIG: {"behat_snapshots_path": "/var/www/html/local/behatsnapshots/snapshots"}
== MOBILE_VERSION: latest-test
== MOBILE_APP_PORT: 80
== PLUGINSTOINSTALL: https://github.com/moodlehq/moodle-local_moodleappbehat.git|local/moodleappbehat|ci;https://github.com/NoelDeMartin/moodle-local_behatsnapshots.git|local/behatsnapshots|main
============================================================================
...
...
>>> startsection Starting Behat main run at Tue Oct 31 21:33:09 CET 2023 <<<
============================================================================
Running: php admin/tool/behat/cli/run.php --format=moodle_progress --out=std --format=pretty --out=/shared/pretty.txt --format=junit --out=/shared/log.junit --profile=chrome --tags=@app&&@local_behatsnapshots

>>> Behat run 1 at Tue Oct 31 21:33:09 CET 2023 <<<
Running single behat site:
Moodle 4.4dev (Build: 20231027), 859df15e73a331198adc43f957ab5e033b3c26ca
Php: 8.1.24, pgsql: 13.12 (Debian 13.12-1.pgdg120+1), OS: Linux 6.4.16-linuxkit x86_64
Run optional tests:
- Accessibility: Yes
Server OS "Linux", Browser: "chrome"
Started at 01-11-2023, 04:33
..F-

--- Failed steps:

001 Scenario: It works in the app.            # /var/www/html/local/behatsnapshots/tests/behat/snapshots.feature:21
      Then the HTML should match the snapshot # /var/www/html/local/behatsnapshots/tests/behat/snapshots.feature:23
        │ You can compare the differences looking at the files in /var/www/html/local/behatsnapshots/snapshots/failures/.
        Snapshots don't match (Behat\Mink\Exception\ExpectationException)

1 scenario (1 failed)
4 steps (2 passed, 1 failed, 1 skipped)
0m10.38s (51.21Mb)
``` 

Is that correct? Only 1 scenario and failing? Or maybe the output above means that not everything is being run?

I was expecting more scenarios to be there (and to get some passing, heh).

Ciao :-)

**Comment by stronk7** [comment]
Now I've run it only with the `--tags=@local_behatsnapshots` and this is what I've got:

```
Running: php admin/tool/behat/cli/run.php --format=moodle_progress --out=std --format=pretty --out=/shared/pretty.txt --format=junit --out=/shared/log.junit --profile=chrome --tags=@local_behatsnapshots

>>> Behat run 1 at Wed Nov  1 10:12:22 CET 2023 <<<
Running single behat site:
Moodle 4.4dev (Build: 20231027), 859df15e73a331198adc43f957ab5e033b3c26ca
Php: 8.1.24, pgsql: 13.12 (Debian 13.12-1.pgdg120+1), OS: Linux 6.4.16-linuxkit x86_64
Run optional tests:
- Accessibility: Yes
Server OS "Linux", Browser: "chrome"
Started at 01-11-2023, 17:12
...........F-

--- Failed steps:

001 Scenario: It works in the app.            # /var/www/html/local/behatsnapshots/tests/behat/snapshots.feature:21
      Then the HTML should match the snapshot # /var/www/html/local/behatsnapshots/tests/behat/snapshots.feature:23
        │ You can compare the differences looking at the files in /var/www/html/local/behatsnapshots/snapshots/failures/.
        Snapshots don't match (Behat\Mink\Exception\ExpectationException)

3 scenarios (2 passed, 1 failed)
13 steps (11 passed, 1 failed, 1 skipped)
0m14.18s (51.64Mb)
```

Is that the expected result?

**Comment by NoelDeMartin** [comment]
Thanks for trying it out @stronk7, all the tests should pass but I haven't run those in a while so it's possible that some HTML in the app has actually changed. I wouldn't bother checking it though, if 2 of the 3 scenarios are passing it means that some of the snapshot comparisons is working.

In any case, I think those tests would pass even without any config changes because they work with the defaults. But if the feature you're implementing allows customizing plugin config, that should be enough. No need to test it with this plugin, if there's anything broken it'll probably be in the side of the plugin and I'll fix it.

**Comment by stronk7** [comment]
I think that we can consider this done as part of #111. It's still in a dev (split) branch, but we already have a few jobs @ CIs using it, some app ones included.

**Comment by NoelDeMartin** [comment]
Ok thanks @stronk7, I'm closing this then.

**Pull request closed without merging**
