### PR TITLE
Add support for specifying the DB tags (versions) to use

### PR DESCRIPTION
**Pull request by stronk7**
Added a new parameter, DBTAG, which behaviour is as follows:

- If not specified, every database will use the currently
  pinned version (if there is any) or "latest" if not. Right now,
  the versions are:
    - mariadb: 10.7
    - mysqli: 5.7
    - oracle: latest (11)
    - pgsql: 12
    - sqlsrv: 2017-latest
- If specified, then that tag will be used, say, for example:
    - mariadb: 10.6, 10.5,...
    - mysqli: 8.0,...
    - oracle: 19, 21,...
    - sqlsrv: 2019-latest,....

So, this change doesn't make any difference in current default
jobs (only pgsql has been raised to 12 to be ready for 4.1). Everything
will continue running exactly as it's now.

Only when we add support for that new DBTAG parameter in jobs (and in
nightlyjobs) is when we'll be able to run alternative versions.

I've run locally all them, both defaults and custom ones and everything
seems to be working ok, going to make some runs now @ ci.moodle.org.

Edited: Removed the WIP note, because this seems to be ready.

### CODE REVIEW

**Comment by stronk7** [comment]
Here there are some runs using the testing branch, just to verify that everything continues working ok:

- pgsql: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/7232/)
- mysqli: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/7233/)
- mariadb: [Build Status](https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/7234/)
- sqlsrv: [!https://ci.moodle.org/buildStatus/icon?job=DEV.02+-+Developer-requested+PHPUnit&build=7235!|https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/7235/]
- oci: [!https://ci.moodle.org/buildStatus/icon?job=DEV.02+-+Developer-requested+PHPUnit&build=7236!|https://ci.moodle.org/view/Testing/job/DEV.02%20-%20Developer-requested%20PHPUnit/7236/]

Once all the above pass, I think it's safe to merge this. Ciao :-)

**Comment by stronk7** [comment]
This is part of [MDLSITE-6376](https://tracker.moodle.org/browse/MDLSITE-6376) but also will help with [MDL-71747](https://tracker.moodle.org/browse/MDL-71747) (Moodle 4.1 requirements changes)

**Review by rezaies — APPROVED** [review]
Thank you. The changes make sense to me.

**Comment by stronk7** [comment]
Thanks, @rezaies ! Self-merged.

**Pull request merged**
