### PR TITLE
Add W3C Support to the CI runner

### PR DESCRIPTION
**Pull request by andrewnicols**
This set of commits adds W3C support to the CI runner.

Backwards compatability with older versions of Moodle is maintained via inspection of the composer.json. If the `instaclick` package is mentioned in the composer.json, then marionette is disabled, and Firefox 47.0.1 is used. No version-specific hacks are required for Chrome.

Additional commits also add support for headless runs, and increased verbosity.

### CODE REVIEW

**Comment by andrewnicols** [comment]
Legacy jobs:

Chrome: https://ci.moodle.org/view/Testing/job/DEV.01%20-%20Developer-requested%20Behat/10842/
Firefox: https://ci.moodle.org/view/Testing/job/DEV.01%20-%20Developer-requested%20Behat/10843/

See MDL-66979 for evidence that this works with W3C :)

**Comment by andrewnicols** [comment]
Test (regression) jobs ran successfully, and the W3C jobs are fine too.

**Comment by andrewnicols** [comment]
Just occurred to try a slightly different approach which will make this arguably more readable.

Kicked off jobs here:

https://ci.moodle.org/view/Testing/job/DEV.01%20-%20Developer-requested%20Behat/10870/
https://ci.moodle.org/view/Testing/job/DEV.01%20-%20Developer-requested%20Behat/10871/

If they're happy then I'll squash and re-push.

**Comment by andrewnicols** [comment]
Note: New idea is on the testing branch and uses array_merge_recursive instead.

**Comment by andrewnicols** [comment]
Good to go for merging.

**Review by stronk7 — COMMENTED** [review]
Hi @andrewnicols ,

this looks 99% correct and, apparently, it's 100% BC for old runs, so yay!

Here there are the only comments I've annotated when reviewing this, surely none of them is a required change, but for your consideration:

1. Do we want verbosity (`BROWSER_DEBUG`) to be available from jenkins (nightlyjobs) DEV runs? I know it's apart from this, just popping the question up.
2. It surprised to me that we are moving away from unique "default" profile and instead going to "chrome" & "firefox" ones.
No big problem, just saying that "default" could have been kept exactly the same and then, conditionally, add the chrome/firefox particularities clearer, say using some, process_chrome_profile() / process_firefox_profile() functions. Just sharing because it's how I was imagining it, no change required.
3. How [can this](https://github.com/moodlehq/moodle-ci-runner/pull/43/files#diff-bbc3de4f3fa0cab9f9523180da30dd81b63b7240c6fdaec67059032ab80a29d4R133) ever exist? Meaning, do we really need that check?
4. Haven't checked if [these "extra" profiles](https://github.com/moodlehq/moodle-ci-runner/pull/43/files#diff-bbc3de4f3fa0cab9f9523180da30dd81b63b7240c6fdaec67059032ab80a29d4L93-L96) are used, just commenting about them because the removal called my attention and now we are not creating them anymore.  Maybe they were unused?
5. Maybe it will be easier to find all the code calculating selenium versions if we move [this code](https://github.com/moodlehq/moodle-ci-runner/pull/43/files#diff-27f51ad2cbe1e28c35ed4c2f9854c8e5f4d1f72abc15636352ecb7f4db42a20cR654-R658) some lines above, where we are pinning chrome? That way all the exceptions / calculations about selenium images are together. I'm happy either way, it's only a tiny detail.

And that's all so far, good stuff!

**Comment by andrewnicols** [comment]
Thanks Eloy,

1: Potentially, yes. I thought I'd add it now to the runner so that we can add it if we want in future
2: There seems to be some change where the values in the `default` profile are not overridable with the new Mink Driver
I have created a new class and set of functions to make this easier to understand and apply anyway.
3: Damn... I thought I'd removed that already!
4: Good catch. I'd missed that, though it seemed to be working anyway and sharing the load. I'm not quite sure how... may be something to do with those defaults being hard set. Either way, I've changed this to copy the default profile to numbered ones and set the `--profile=` argument to "$browser{runprocess}" so that it is rewritten to chrome1 etc.
4: Done :)

Jobs:
Chrome current integration: https://ci.moodle.org/view/Testing/job/DEV.01%20-%20Developer-requested%20Behat/10905/
Firefox current integration: https://ci.moodle.org/view/Testing/job/DEV.01%20-%20Developer-requested%20Behat/10906/

Chrome with 66979:  https://ci.moodle.org/view/Testing/job/DEV.01%20-%20Developer-requested%20Behat/10903/
Firefox with 66979:  https://ci.moodle.org/view/Testing/job/DEV.01%20-%20Developer-requested%20Behat/10904/

Chrome with 66979 and a deliberate breakage (rerun):  https://ci.moodle.org/view/Testing/job/DEV.01%20-%20Developer-requested%20Behat/10907/
Chrome with breakage and single run (no parallel):  https://ci.moodle.org/view/Testing/job/DEV.01%20-%20Developer-requested%20Behat/10908/

**Comment by andrewnicols** [comment]
To be on the safe side with the release we should possibly wait til Monday to land this

**Comment by stronk7** [comment]
Have just tagged minor releases (only version.php changes), so I'm going to merge this now. That way we'll get the first runs of the runner along the weekend (it doesn't matter much if they fail or no regarding Monday releases).

**Comment by stronk7** [comment]
Merged, thanks!

**Pull request merged**
