### PR TITLE
Change mobile by app

### LINKED ISSUE #25: Change moodlehq/moodlemobile2 to moodlehq/moodleapp
The former has been deprecated, the later is the new one

### PR DESCRIPTION
**Pull request by stronk7**
- docker image (already done by #23)
- script variable (keeping BC with old one)

This fixes #25

### CODE REVIEW

**Comment by stronk7** [comment]
If accepted, I'll change the ci.moodle.org job to the new one, also nightlyjobs will receive a few modifications (to complete the mobile to app renaming).

Also, note that the old param still works perfectly:

```
<<< run of @app coming soon >>>
```

**Comment by stronk7** [comment]
BTW, I'm getting some failures with the @app tests, grrr. But I don't think they can be related to this change, also have faced the same results while reviewing another PR, similar to this, but in the moodle-docker alternative. Hate instability, grrr.

**Comment by stronk7** [comment]
Have tried everything I can imagine and I get practically all the tests failing here with strange JS/AJAX slow errors. Have tried updating docker, switching to stable (was using edge...) same results. @ CI it seems to be running ok. Also I got them passing here once @ https://github.com/moodlehq/moodle-docker/pull/122 but immediately after that, back to failures.

Would be great if you can test it in your environment...

**Comment by andrewnicols** [comment]
I'm seeing failures in all scenarios, but for me it's different.

My failures are all:

```
020 Scenario: Next and previous navigation in the 3.7 app # /var/www/html/local/moodlemobileapp/mod/quiz/tests/behat/app_quiz_navigation.feature:71
      Given I enter the app                               # /var/www/html/local/moodlemobileapp/mod/quiz/tests/behat/app_quiz_navigation.feature:72
        Error setting field - ERROR: No matches for text (Behat\Mink\Exception\DriverException)
```

**Comment by stronk7** [comment]
For the records, I'm trying with `$CFG->behat_increasetimeout = 3`, @sarjona suggested that it made a difference for her in the past.

I'm really worried that my brand-new laptop with 8 cores / 8Gb RAM dedicated to docker is unable to run that in time, with the latop doing nothing but that, grrr. Let's see...

**Comment by stronk7** [comment]
I'm cross-posting from https://github.com/moodlehq/moodle-docker/pull/122

I really don't understand what's going with the ionic docker image, since the run above yesterday, I've been unable to complete any other run (@ https://github.com/moodlehq/moodle-ci-runner/pull/26).

- I've tried pruning everything and restarting docker.
- I've tried increasing the behat timeout to `$CFG->behat_increasetimeout = 2;` still getting lots of AJAX/JS timeouts (right now I'm trying with the timeout set to 5 (that means 50 seconds!).
- Sometimes the image does not start, exiting in the middle of the startup.

Note it's not related with this issue, just sharing in case you can imagine any reason. My laptop is basically idle and only running those attempts (and it's a brand-new rmbp, plenty of processors and ram).

And for some reason, those ionic images (have tried both "next" and "latest") are really slow here, grrr.

Ciao :-)

**Comment by stronk7** [comment]
This is what I'm getting with the crazy 50 seconds timeout (no more AJAX/JS timeouts, but still a good number of failures): https://pastebin.com/NVvFH5WP

**Comment by stronk7** [comment]
I give up, just for reference:

1. whenever this renaming is tried in the future, it also requires changes @ nightlyjobs (bridge between jenkins a moodle-ci-runner).
2. I had added a new job to ToBiC to always run \@app tests, see https://github.com/moodlehq/moodle-local_ci/pull/215 ...
tobic_app
... but it's failing also @ CIs so better keep it apart until we get some stability there.

Ciao :-)

**Pull request closed without merging**
