### PR TITLE
Add bigbluebutton mock server support

### PR DESCRIPTION
**Pull request by vmdef**
BBB is just to be integrated, so we need the mock server ready :D

### CODE REVIEW

**Comment by stronk7** [comment]
Hi, a few questions:

1. Is the mock server needed for both phpunit and behat?
2. Maybe we should move it to 'moodlehq' repo/image (from current @andrewnicols one?).
3. Surely this will need to, also be added to [moodle-docker](https://github.com/moodlehq/moodle-docker), to keep them feature-paired.

**Comment by vmdef** [comment]
Hi @stronk7,

> 1. Is the mock server needed for both phpunit and behat?

I had the same question. I quote Andrew's answer:

> Yes. Unfortunately this was not possible for a variety of reasons. Initally we did mock this but it was not testable using GHA or Travis with Behat becaues those approaches use a php in server mode, which is single-threaded. Once it was mocked for Behat it made sense to use the same mock for PHPUnit too.

> 2. Maybe we should move it to 'moodlehq' repo/image (from current @andrewnicols one?).

I think so. Is the following the right way?

- Create a new repository in GitHub (moodlehq).
- Push from a local copy of the Andrews' repo to the repository created in the previous step.

> 3. Surely this will need to, also be added to [moodle-docker](https://github.com/moodlehq/moodle-docker), to keep them feature-paired.

Well spotted. It would be enough to add a new service in [base.yml](https://github.com/moodlehq/moodle-docker/blob/master/base.yml)?

**Comment by stronk7** [comment]
About 2. I'm happy either way, it can be both @andrewnicols transferring the repo to moodlehq, or moodlehq forking/cloning from Andrew's... whatever works ok for him...

About 3. I'd create at very least an issue @ moodle-docker, there is a specific setting for extra services (ldap, memcached...) and surely this will need to be loaded that way (not by default but when those supplemental services are enabled).

**Comment by andrewnicols** [comment]
My original hope had been that Blindside would want me to xfer the image there but there's been no movement on that front.

I'll xfer to moodlehq instead now.

**Comment by andrewnicols** [comment]
Note: It will need some assistance in getting deploy keys for building in gha to dockerhub

**Comment by stronk7** [comment]
Ok, so the images are already available @ DockerHub:

https://hub.docker.com/r/moodlehq/bigbluebutton_mock/tags

(we are still doing the changes needed to also publish them @ github's own registry)

This implies that we can modify this PR to point to the new (moodlehq) image.

**Comment by stronk7** [comment]
Merged, thanks!

**Pull request merged**
